function varargout=AppelCast3M(NameCastem,varargin)
% AppelCast3M : Interface between Castem16 and Matlab via ACQU input
% and SORT 'EXCE' 'SEPA' 'ESPA' output (Only for Scalar Outputs)
%
% V1 - Stéphane Nachar - 27/05/2016
%
% Inputs :
% NameCastem : Name of the Cast3M Function
% Varargin   : Inputs Value
% Outputs :
% Varargout  : Output value
% Parameters :
% FolderTemp : Temporary folder for datas
% FolderFct  : Folder for Cast3M Scripts
% OutputName : Name of the CSV Output file generated by Cast3M

FolderTemp = fullfile(pwd,'Temp');
FolderFct  = fullfile(pwd,'Fonctions');
OutputName = 'out.csv';

%% Create Temp folder
Alea = num2str(now*1E9,'%1.0f');
FolderTemp = fullfile(FolderTemp,Alea);
mkdir(FolderTemp);
copyfile(fullfile(FolderFct,NameCastem),fullfile(FolderTemp,NameCastem));

% Open file
fileID = fopen(fullfile(FolderTemp,'data.in'),'w');
for argin = varargin
    fprintf(fileID,[num2str(argin),'\n']);
end
status = fclose(fileID);
if status~=0
    warning('Unable to close input file');
end

%% Start Cast3M
status = system(sprintf('cd %s && castem16 %s',FolderTemp,NameCastem));
if status~=0
    warning('Error when executing Cast3M');
end

%% Output data
fileID = fopen(fullfile(FolderTemp,OutputName),'r');

% open the file
fid = fopen(filename);

% make sure the file is not empty
finfo = dir(filename);
fsize = finfo.bytes;

if fsize > 0 

    % read the file
    block = 1;
    while ~feof(fid)
        varargout{block}=str2double(fscanf(fileID,'%f'));
        block = block + 1;
    end
end
% close the file
status=fclose(fileID);
if status~=0
    warning('Unable to close output file');
end
end
